/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#181c1e",
        "surface-container-high": "#e5e9eb",
        "on-primary-fixed": "#001b3c",
        "on-tertiary-fixed": "#001c38",
        surface: "#f7fafc",
        "on-tertiary-fixed-variant": "#004881",
        "tertiary-fixed-dim": "#a2c9ff",
        "on-secondary-container": "#58646a",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff",
        "inverse-primary": "#adc7f7",
        "surface-bright": "#f7fafc",
        "outline-variant": "#c4c6cf",
        "surface-container-lowest": "#ffffff",
        outline: "#74777f",
        "surface-tint": "#455f88",
        "surface-variant": "#e0e3e5",
        "on-error-container": "#93000a",
        "on-surface-variant": "#43474e",
        background: "#f7fafc",
        "on-secondary-fixed-variant": "#3c494e",
        tertiary: "#002141",
        "primary-fixed-dim": "#adc7f7",
        "error-container": "#ffdad6",
        "primary-container": "#1a365d",
        primary: "#002045",
        "surface-dim": "#d7dadc",
        "on-primary-fixed-variant": "#2d476f",
        "primary-fixed": "#d6e3ff",
        "surface-container": "#ebeef0",
        "surface-container-low": "#f1f4f6",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eef1f3",
        "on-tertiary-container": "#68a2e9",
        "on-primary": "#ffffff",
        "on-background": "#181c1e",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#d8e4eb",
        "secondary-fixed-dim": "#bcc8cf",
        "on-primary-container": "#86a0cd",
        "on-secondary-fixed": "#111d22",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d5e2e9",
        secondary: "#546066",
        "tertiary-fixed": "#d3e4ff",
        "tertiary-container": "#003765",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        "sidebar-width": "280px",
        "container-max": "1440px",
        gutter: "24px",
        base: "8px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
